// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDiskAccess() {
  return window['go']['main']['App']['CheckDiskAccess']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DownloadAndInstallUpdate() {
  return window['go']['main']['App']['DownloadAndInstallUpdate']();
}

export function GetActivityLog() {
  return window['go']['main']['App']['GetActivityLog']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function OpenSystemPrefs() {
  return window['go']['main']['App']['OpenSystemPrefs']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveSetup(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSetup'](arg1, arg2, arg3);
}
