// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {agent} from '../models';

export function CheckDiskAccess():Promise<boolean>;

export function CheckForUpdate():Promise<main.UpdateStatus>;

export function DownloadAndInstallUpdate():Promise<main.UpdateStatus>;

export function GetActivityLog():Promise<Array<agent.LogEntry>>;

export function GetCurrentVersion():Promise<string>;

export function GetStatus():Promise<agent.StatusInfo>;

export function IsConfigured():Promise<boolean>;

export function OpenSystemPrefs():Promise<void>;

export function RestartApp():Promise<void>;

export function SaveSetup(arg1:string,arg2:string,arg3:string):Promise<void>;
